# vim:fileencoding=utf-8:ft=conf:foldmethod=marker
placement_strategy top-left
editor nvim
shell fish
hide_window_decorations yes
map ctrl+shift+d launch --cwd=current --type=tab
map ctrl+shift+enter new_window_with_cwd 
enabled_layouts tall, horizontal
map ctrl+shift+tab focus_visible_window
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window top
map ctrl+shift+down neighboring_window bottom

map ctrl+alt+right next_tab
map ctrl+alt+left previous_tab
# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
