console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  air-force-blue = '#698996'
  black = '#262B44'
  blue = '#4B95E9'
  cambridge-blue = '#97B1A6'
  carribean-current = '#407076'
  feldgrau = '#466060'
  green = '#59C9A5'
  kinda-blue = '#59858b'
  light-pink = '#d57b9a'
  lighter-green = '#c7f0e1'
  orange = '#F07623'
  puce = '#C581A3'
  purple = '#850EEB'
  quinacridone-magenta = '#8E4162'
  red = '#D81E5B'
  tea-rose = '#EBBAB9'
  text = '#494D64'
  timberwolf = '#C9C5BA'
  white = '#E0DEF4'
  yellow = '#F3AE35'

[secondary_prompt]
  template = '<p:yellow,transparent> </><,p:yellow> > </><p:text,transparent> </> '
  foreground = 'p:text'
  background = 'transparent'

[transient_prompt]
  template = '<#8AADF4,transparent></><,#8AADF4> {{ .Folder }} </><#8AADF4,transparent></>'
  foreground = 'p:text'
  background = 'p:tea-rose'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
    foreground = 'p:text'
    powerline_symbol = ''
    background = '#8AADF4'
    type = 'session'
    style = 'diamond'
    min_width = 100

    [blocks.segments.properties]

  [[blocks.segments]]
    template = '  {{ path .Path .Location }} '
    foreground = 'p:text'
    powerline_symbol = ''
    background = '#B7BDF8'
    type = 'path'
    style = 'powerline'
    min_width = 100

    [blocks.segments.properties]
      style = 'unique'

  [[blocks.segments]]
    template = '{{.Path}}'
    foreground = 'p:tea-rose'
    type = 'path'
    style = 'plain'
    max_width = 99

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template= ' {{.ChangeID}}{{if .Working.Changed}}{{ .Working.String }}{{ end }} '
    type = "jujutsu"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#193549"
    background = "#ffeb3b"
    min_width = 100

    [options]
    fetch_status = true
    ignore_working_copy = false
    fetch_ahead_counter = true
    ahead_icon = "⇡"

  [[blocks.segments]]
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:cambridge-blue'
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:text{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:text{{ end }}', '{{ if gt .Ahead 0 }}p:text{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#e0d1cd{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}p:lighter-green{{ end }}', '{{ if gt .Behind 0 }}p:kinda-blue{{ end }}']
    min_width = 100

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '   '
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:timberwolf'
    type = 'root'
    style = 'powerline'
    min_width = 100

    [blocks.segments.properties]

  [[blocks.segments]]
    leading_diamond = '<transparent,background></>'
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    foreground = 'p:text'
    powerline_symbol = ''
    background = '#F5BDE6'
    type = 'status'
    style = 'powerline'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    min_width = 100

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    template = '>'
    foreground = 'p:purple'
    type = 'text'
    style = 'plain'
    max_width = 99

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    template = ' {{ .Full }}'
    foreground = '#193549'
    powerline_symbol = ''
    background = '#99908a'
    type = 'rust'
    style = 'powerline'
    min_width = 100

  [[blocks.segments]]
    template = ' {{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}'
    fetch_virtual_env = true
    foreground = '#100e23'
    powerline_symbol = ''
    background = '#906cff'
    type = 'python'
    style = 'powerline'
    min_width = 100

    [blocks.segments.properties]
      display_mode = 'files'

